import { RoomLayout } from "./types";

export const roomLayout: RoomLayout = {
  schemaVersion: "0.1.0",
  width: 960,
  height: 640,
  tileSize: 40,
  spawn: { x: 470, y: 480 },
  floor: {
    base: "#d8c39f",
    grid: "rgba(82, 130, 116, 0.22)",
  },
  furniture: [
    {
      id: "warm-rug",
      kind: "rug",
      x: 310,
      y: 285,
      width: 320,
      height: 175,
      color: "#bd6f57",
      blocksMovement: false,
    },
    {
      id: "coffee-table",
      kind: "table",
      label: "Table",
      x: 375,
      y: 328,
      width: 170,
      height: 68,
      color: "#8b5a36",
      blocksMovement: true,
    },
    {
      id: "left-sofa",
      kind: "sofa",
      label: "Sofa",
      x: 100,
      y: 380,
      width: 205,
      height: 86,
      color: "#4f8f8a",
      blocksMovement: true,
    },
    {
      id: "right-sofa",
      kind: "sofa",
      label: "Sofa",
      x: 690,
      y: 145,
      width: 205,
      height: 86,
      color: "#b9864b",
      blocksMovement: true,
    },
    {
      id: "left-plant",
      kind: "plant",
      x: 60,
      y: 78,
      width: 64,
      height: 116,
      color: "#3d8f62",
      blocksMovement: true,
    },
    {
      id: "right-plant",
      kind: "plant",
      x: 810,
      y: 498,
      width: 64,
      height: 116,
      color: "#3d8f62",
      blocksMovement: true,
    },
    {
      id: "notice-board",
      kind: "board",
      label: "Today\nShip pet lobby",
      x: 735,
      y: 56,
      width: 160,
      height: 96,
      color: "#fff8df",
      blocksMovement: true,
    },
  ],
  guests: [
    { id: "miso", name: "Miso", status: "chatting", color: "#9ad7c2", x: 250, y: 330, phase: 0 },
    { id: "nori", name: "Nori", status: "planning", color: "#f4b65f", x: 650, y: 250, phase: 1.2 },
    { id: "boba", name: "Boba", status: "idle", color: "#d9b8ff", x: 610, y: 500, phase: 2.4 },
  ],
};
